# Generated by Django 2.0 on 2018-09-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fractalweb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='category',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=555, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.IntegerField(blank=True, default=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rollno',
            field=models.IntegerField(blank=True, default=170, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='branch',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
